Algoritmo "tabuada 3"
// 
//  
// Descrição   : tabuada usando repita
// Autor(a)    : Miguel Oliveira de Araújo
// Data atual  : 05/04/2023
Var
// Seção de Declarações das variáveis 
x, r:real
i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("qual numero você quer ter a tabuada?")
leia(x)
i:=1
repita
r:=x*i
escreva(x,"x",i,"=",r)
i:=1+1
ate(1>10)
Fimalgoritmo